"""add settings to projects

Revision ID: acfd0cd9928c
Revises: 008_hardening_fixes
Create Date: 2026-04-30 14:04:50.827493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'acfd0cd9928c'
down_revision: Union[str, Sequence[str], None] = '008_hardening_fixes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('benchmark_runs', sa.Column('overall_score', sa.Float(), nullable=False))
    op.add_column('benchmark_runs', sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('benchmark_runs', 'score')
    op.drop_column('benchmark_runs', 'model')
    op.drop_column('benchmark_runs', 'details')
    op.drop_column('benchmark_runs', 'scenario')
    op.drop_index(op.f('ix_memories_ttl_expires_at'), table_name='memories', postgresql_where='(expires_at IS NOT NULL)')
    op.create_index(op.f('ix_memories_expires_at'), 'memories', ['expires_at'], unique=False)
    op.add_column('projects', sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('projects', 'attention_weights')
    op.alter_column('users', 'github_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.create_index(op.f('ix_webhook_deliveries_delivered_at'), 'webhook_deliveries', ['delivered_at'], unique=False)
    op.create_index(op.f('ix_webhooks_project_id'), 'webhooks', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhooks_project_id'), table_name='webhooks')
    op.drop_index(op.f('ix_webhook_deliveries_delivered_at'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.alter_column('users', 'github_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.add_column('projects', sa.Column('attention_weights', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('projects', 'settings')
    op.drop_index(op.f('ix_memories_expires_at'), table_name='memories')
    op.create_index(op.f('ix_memories_ttl_expires_at'), 'memories', ['expires_at'], unique=False, postgresql_where='(expires_at IS NOT NULL)')
    op.add_column('benchmark_runs', sa.Column('scenario', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('benchmark_runs', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('benchmark_runs', sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('benchmark_runs', sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('benchmark_runs', 'results')
    op.drop_column('benchmark_runs', 'overall_score')
    # ### end Alembic commands ###
